spring:
  profiles:
    active: local

---
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  profiles: local
#  datasource:
    #    platform: hsqldb
    #    initialization-mode: always
  #    continue-on-error: false
  jpa:
    #properties:
    #  hibernate:
    #    dialect: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
